import { render } from 'solid-js/web';
import { createSignal } from 'solid-js';
import WorkflowDesigner from '../src/components/WorkflowDesigner';

// Mock tool definitions for testing
const MOCK_TOOLS = [
  {
    id: 'fs.read_file',
    name: 'Read File',
    description: 'Read contents of a file',
    input_schema: {
      type: 'object',
      properties: {
        path: { type: 'string', description: 'File path to read' },
        encoding: { type: 'string', description: 'File encoding', enum: ['utf-8', 'ascii', 'binary'] },
      },
      required: ['path'],
    },
    output_schema: { type: 'object', properties: { content: { type: 'string' } } },
  },
  {
    id: 'fs.write_file',
    name: 'Write File',
    description: 'Write contents to a file',
    input_schema: {
      type: 'object',
      properties: {
        path: { type: 'string', description: 'File path to write' },
        content: { type: 'string', description: 'Content to write' },
      },
      required: ['path', 'content'],
    },
    output_schema: null,
  },
  {
    id: 'http.request',
    name: 'HTTP Request',
    description: 'Make an HTTP request',
    input_schema: {
      type: 'object',
      properties: {
        url: { type: 'string', description: 'Request URL' },
        method: { type: 'string', description: 'HTTP method', enum: ['GET', 'POST', 'PUT', 'DELETE'] },
        body: { type: 'object', description: 'Request body' },
        timeout: { type: 'number', description: 'Timeout in seconds' },
      },
      required: ['url'],
    },
    output_schema: { type: 'object', properties: { status: { type: 'number' }, body: { type: 'string' } } },
  },
];

// Simple workflow YAML matching the format generated by toYaml()
const INITIAL_YAML = `name: test-workflow
version: '1'
description: A test workflow
variables:
  type: object
  required:
    - input_file
  properties:
    input_file:
      type: string
      description: Input file path
    output_file:
      type: string
      description: Output file path
steps:
  - id: trigger_0
    type: trigger
    trigger:
      type: manual
      inputs: []
  - id: read_step
    type: task
    task:
      kind: call_tool
      tool_id: fs.read_file
      arguments:
        path: '{{variables.input_file}}'
    next:
      - write_step
  - id: write_step
    type: task
    task:
      kind: call_tool
      tool_id: fs.write_file
      arguments:
        path: '{{variables.output_file}}'
        content: '{{steps.read_step.outputs.result}}'
`;

function TestHarness() {
  const [yamlOutput, setYamlOutput] = createSignal('');
  const [changeCount, setChangeCount] = createSignal(0);

  return (
    <div style={{ width: '100vw', height: '100vh', display: 'flex', 'flex-direction': 'column' }}>
      {/* Status bar for test assertions */}
      <div
        id="test-status-bar"
        style={{
          height: '28px', 'min-height': '28px',
          background: '#11111b', padding: '0 12px',
          display: 'flex', 'align-items': 'center', gap: '16px',
          'font-size': '0.75em', color: '#a6adc8',
          'border-bottom': '1px solid #313244',
        }}
      >
        <span>Changes: <span id="change-count">{changeCount()}</span></span>
        <span>YAML length: <span id="yaml-length">{yamlOutput().length}</span></span>
        <span id="heartbeat" data-alive="true">♥ alive</span>
      </div>
      {/* Designer */}
      <div style={{ flex: '1', overflow: 'hidden' }}>
        <WorkflowDesigner
          initialYaml={INITIAL_YAML}
          onYamlChange={(yaml) => {
            setYamlOutput(yaml);
            setChangeCount(c => c + 1);
          }}
          toolDefinitions={MOCK_TOOLS}
        />
      </div>
    </div>
  );
}

render(() => <TestHarness />, document.getElementById('root')!);

// Heartbeat: update a timestamp every 500ms so Playwright can detect freezes
setInterval(() => {
  const el = document.getElementById('heartbeat');
  if (el) {
    el.dataset.ts = String(Date.now());
  }
}, 500);
